import { Token } from "@/types/token";

export const mockTokens: Token[] = [

  {
    id: "1",
    name: "Ethereum",
    symbol: "ETH",
    price: 2452.88,
    change24h: 2.11,
    volume: 12400000,
    status: "NEW",
    icon: "/tokens/eth.png",
  },
  {
    id: "2",
    name: "Solana",
    symbol: "SOL",
    price: 98.06,
    change24h: -2.18,
    volume: 8400000,
    status: "NEW",
    icon: "/tokens/sol.png",
  },
  {
    id: "3",
    name: "Avalanche",
    symbol: "AVAX",
    price: 35.49,
    change24h: 3.11,
    volume: 5100000,
    status: "NEW",
    icon: "/tokens/avax.png",
  },
  {
    id: "4",
    name: "Sui",
    symbol: "SUI",
    price: 1.90,
    change24h: 5.07,
    volume: 3900000,
    status: "NEW",
    icon: "/tokens/sui.png",
  },
  {
    id: "5",
    name: "Celestia",
    symbol: "TIA",
    price: 14.82,
    change24h: -1.04,
    volume: 2200000,
    status: "NEW",
    icon: "/tokens/tia.png",
  },
  {
    id: "6",
    name: "Injective",
    symbol: "INJ",
    price: 38.12,
    change24h: 4.66,
    volume: 6400000,
    status: "NEW",
    icon: "/tokens/inj.png",
  },

 
  {
    id: "7",
    name: "Arbitrum",
    symbol: "ARB",
    price: 1.23,
    change24h: 4.78,
    volume: 12500000,
    status: "FINAL",
    icon: "/tokens/arb.png",
  },
  {
    id: "8",
    name: "Optimism",
    symbol: "OP",
    price: 2.41,
    change24h: -1.32,
    volume: 6800000,
    status: "FINAL",
    icon: "/tokens/op.png",
  },
  {
    id: "9",
    name: "Aptos",
    symbol: "APT",
    price: 8.92,
    change24h: 0.64,
    volume: 4700000,
    status: "FINAL",
    icon: "/tokens/apt.png",
  },
  {
    id: "10",
    name: "Near Protocol",
    symbol: "NEAR",
    price: 6.15,
    change24h: -0.87,
    volume: 5300000,
    status: "FINAL",
    icon: "/tokens/near.png",
  },
  {
    id: "11",
    name: "Sei",
    symbol: "SEI",
    price: 0.68,
    change24h: 3.92,
    volume: 2600000,
    status: "FINAL",
    icon: "/tokens/sei.png",
  },
  {
    id: "12",
    name: "Mantle",
    symbol: "MNT",
    price: 0.61,
    change24h: -0.42,
    volume: 3100000,
    status: "FINAL",
    icon: "/tokens/mnt.png",
  },


  {
    id: "13",
    name: "Polygon",
    symbol: "MATIC",
    price: 0.72,
    change24h: -1.02,
    volume: 4300000,
    status: "MIGRATED",
    icon: "/tokens/matic.png",
  },
  {
    id: "14",
    name: "Fantom",
    symbol: "FTM",
    price: 0.54,
    change24h: 2.11,
    volume: 2800000,
    status: "MIGRATED",
    icon: "/tokens/ftm.png",
  },
  {
    id: "15",
    name: "Celo",
    symbol: "CELO",
    price: 0.63,
    change24h: 1.26,
    volume: 1900000,
    status: "MIGRATED",
    icon: "/tokens/celo.png",
  },
  {
    id: "16",
    name: "Harmony",
    symbol: "ONE",
    price: 0.019,
    change24h: -0.45,
    volume: 1700000,
    status: "MIGRATED",
    icon: "/tokens/one.png",
  },
  {
    id: "17",
    name: "Zilliqa",
    symbol: "ZIL",
    price: 0.028,
    change24h: 0.88,
    volume: 1500000,
    status: "MIGRATED",
    icon: "/tokens/zil.png",
  },
  {
    id: "18",
    name: "Qtum",
    symbol: "QTUM",
    price: 3.12,
    change24h: -1.94,
    volume: 1200000,
    status: "MIGRATED",
    icon: "/tokens/qtum.png",
  },
];
