export const TOKEN_ICONS: Record<string, string> = {
  ETH: "/tokens/eth.png",
  SOL: "/tokens/sol.png",
  AVAX: "/tokens/avax.png",
  SUI: "/tokens/sui.png",
  TIA: "/tokens/tia.png",
  INJ: "/tokens/inj.png",
  SEI:"/tokens/sei.png",
  ARB: "/tokens/arb.png",
  OP: "/tokens/op.png",
  APT: "/tokens/apt.png",
  MNT:"/tokens/mnt.png",
  MATIC: "/tokens/matic.png",
  FTM: "/tokens/ftm.png",
  CELO: "/tokens/celo.png",
  ONE: "/tokens/one.png",
  ZIL: "/tokens/zil.png",
  QTUM: "/tokens/qtum.png",
};
